max_jobs: 1
image: Visual Studio 2017

matrix:
  fast_finish: true

cache:
  - packages
  - tools

platform: Any CPU
configuration: Release

build_script:
  - ps: .\build.ps1

artifacts:
  - path: Titan/*.exe
  - path: Titan/*.dll

test: off
deploy: off
